export const systemList = [
    { name: 'orderSystem', title: '订单系统', port: 8010, activeMenu: '/businessSystem' },
    { name: 'passengerSystem', title: '乘客中心', port: 8011 },
    { name: 'driverSystem', title: '网约车司机中心', port: 8012 },
    { name: 'customerSystem', title: '客情系统', port: 8013 },
    { name: 'activitySystem', title: '营销系统', port: 8002 },
    { name: 'perfSystem', title: '包干绩效', port: 8080 },
    { name: 'sandboxSystem', title: '沙盘推演系统', port: 8014 },
    { name: 'taxiSystem', title: '出租车司机中心', port: 8015 },
    { name: 'thirdpartySystem', title: '第三方服务管理系统', port: 8019 },
    { name: 'projectSystem', title: '项目管理系统', port: 8014 },
    { name: 'inforSystem', title: '信息发布系统', port: 8014 },
    { name: 'couponSystem', title: '卡券系统', port: 8018 },
    { name: 'financeSystem', title: '财务系统', port: 8017, type: 'modules' },
    { name: 'orgSystem', title: '机构管理系统', port: 8020, type: 'modules' },
    { name: 'configSystem', title: '配置管理系统', port: 8012, type: 'modules' },
    { name: 'ehrSystem', title: '智能人事', port: 8019, activeMenu: '/workbench' },
    { name: 'kpiSystem', title: '绩效分管理系统', port: 8003 },
    { name: 'valuationSystem', title: '计价系统', port: 8022, type: 'modules' },
    { name: 'securitySystem', title: '安全中心', port: 8007, type: 'modules' },
    { name: 'riskSystem', title: '风控系统', port: 8023, activeMenu: '/businessSystem' },
    { name: 'judgmentSystem', title: '司乘判责系统', port: 8024, activeMenu: '/businessSystem' },
    { name: 'openplatformSystem', title: '开放平台系统', port: 8025, activeMenu: '/businessSystem' },
    { name: 'marketSystem', title: '新营销系统', port: 8006, activeMenu: '/businessSystem' },
    { name: 'orderManage', title: '订单管理', port: 8008, activeMenu: '/businessSystem' },
    { name: 'businessCarSystem', title: '企业用车管理', port: 8888 },
    { name: 'datacenterSystem', title: '数据中心', port: 9000, activeMenu: '/businessSystem' },
    { name: 'imSystem', title: 'IM信息管理系统', port: 8026, activeMenu: '/businessSystem' },
    { name: 'datascreenSystem', title: '数据大屏', port: 8008 },
    { name: 'newEnergySystem', title: '新能源系统', port: 9002, activeMenu: '/businessSystem' },
    { name: 'dispatchSystem', title: '调度系统', port: 9003, activeMenu: '/businessSystem' },
    { name: 'datareportSystem', title: '监管信息上报系统', port: 9005 },
    { name: 'appLogsManageSystem', title: '日志管理系统', port: 9004, activeMenu: '/systemManage' },
    { name: 'carCenterSystem', title: '车辆中心系统', port: 3333, activeMenu: '/businessSystem' },
    { name: 'advSystem', title: '广告管理系统', port: 5173, activeMenu: '/businessSystem' },
    { name: 'customerServiceSystem', title: '智能客服系统', port: 9030, activeMenu: '/businessSystem' },
    { name: 'checkWorkAttendanceSystem', title: '考勤系统', port: 8027, activeMenu: '/workbench' },
    { name: 'eventTrackingSystem', title: '埋点管理系统', port: 9006 },
    { name: 'daijiakpiSystem', title: '代驾绩效分系统', port: 9007 },
    { name: 'questionbankSystem', title: '题库', port: 8028, activeMenu: '/businessSystem' },
    { name: 'transportSystem', title: '运力商系统', port: 9008, activeMenu: '/businessSystem' },
    { name: 'mallConfigSystem', title: '电商配置管理', port: 9009, activeMenu: '/businessSystem'},
    { name: 'customerSeatsSystem', title: '智能客服座席端', port: 9010, activeMenu: '/workbench' },
    { name: 'customerManageSystem', title: '智能客服管理端', port: 9011, activeMenu: '/workbench' },
    { name: 'djValuationSystem', title: '代驾计价系统', port: 9012, activeMenu: '/businessSystem' },
    { name: 'djDispatchSystem', title: '代驾调度系统', port: 9013, activeMenu: '/businessSystem' },
    { name: 'daijiaOrderSystem', title: '代驾订单系统', port: 9014, activeMenu: '/businessSystem' },
    { name: 'djOrderHotZoneSystem', title: '代驾订单热区', port: 9015, activeMenu: '/workbench' },
    { name: 'daijiaFinanceSystem', title: '代驾财务结算管理', port: 9016, activeMenu: '/workbench' },
    { name: 'djConfigureSystem', title: '代驾配置管理', port: 9017, activeMenu: '/workbench' },
    { name: 'daijiaLumpSumSystem', title: '代驾平台包干管理', port: 9018, activeMenu: '/workbench' },
    { name: 'djDriverCenterSystem', title: '代驾司机中心', port: 9019, activeMenu: '/businessSystem' },
    { name: 'daijiaBusinessSystem', title: '代驾基础业务配置', port: 9020, activeMenu: '/businessSystem' },
    { name: 'djEvaluationSystem', title: '代驾评价管理', port: 9021, activeMenu: '/workbench' },
    { name: 'daijiaLumpSumKpiSystem', title: '代驾包干绩效', port: 9026, activeMenu: '/businessSystem' },
    { name: 'djImputationSystem', title: '代驾判责系统', port: 9029, activeMenu: '/businessSystem' },
    { name: 'daijiaRiskSystem', title: '代驾风控系统', port: 9028, activeMenu: '/businessSystem' },
    { name: 'carLifeSystem', title: '车生活管理', port: 9022, activeMenu: '/businessSystem' },
    { name: 'mallMarketingSystem', title: '电商营销系统', port: 9023, activeMenu: '/mallMarketingSystem' },
    { name: 'mallPlatformSystem', title: '电商平台后台', port: 9024, activeMenu: '/mallPlatformSystem' },
    // 这里是新的仓库地址-和上面老的机构管理系统是完全不冲突的
    { name: 'orgManageSystem', title: '机构管理系统', port: 9025, activeMenu: '/orgManageSystem' },
    { name: 'insuranceSystem', title: '车险管理', port: 5230, activeMenu: '/businessSystem' },
    { name: 'mallSupplierManage', title: '电商供应商管理', port: 9028, activeMenu: '/mallSupplierManage' },
    { name: 'rechargeSystem', title: '充值业务系统', port: 9031, activeMenu: '/rechargeSystem' },
    { name: 'mallOpenSystem', title: '电商开放平台', port: 9032, activeMenu: '/mallOpenSystem' },
    { name: 'intelligenceLifeSystem', title: '智慧生活APP', port: 9033, activeMenu: '/intelligenceLifeSystem' },
    { name: 'smartLifeFinancialSystem', title: '智慧生活财务系统', port: 9034, activeMenu: '/smartLifeFinancialSystem' },
    { name: 'agentManageSystem', title: '智慧生活代理商管理', port: 9035 },
    { name: 'smartLifeUserCenterSystem', title: '智慧生活用户中心', port: 9036 },
    { name: 'newbatterySystem', title: '两轮车管理系统', port: 9188 },
    { name: 'newbatteryControlSystem', title: '电动车中控管理', port: 9027 },
    { name: 'newonlineOrderSystem', title: '电商订单管理', port: 8050, activeMenu: '/workbench' },
    { name: 'opsSystem', title: '运维管理系统', port: 8120, activeMenu: '/businessSystem' },
];
