const state = {
    transportList: [],  // 所有运力商
    businessScenarioExpFilters: [    //业务场景
        {id: 20, value: '实时'},
        {id: 21, value: '预约'},
        {id: 22, value: '扫码'},
        {id: 70, value: '包车'},
        {id: 80, value:"城际专线-乘客订单"}
    ],
    ordinaryTypesFilters: [  //订单风险
        { id: 1, value: '正常' },
        { id: 2, value: '疑似风险' },
    ],
    ordinaryPayMethodFilters: [    //订单支付方式
        { id: 1, value: '支付宝' },
        { id: 2, value: '微信' },
        { id: 3, value: '余额支付' },
        { id: 4, value: '微信+余额' },
        { id: 5, value: '支付宝+余额' },
        { id: 6, value: '企业支付' },
        { id: 7, value: '开放平台支付' },
        { id: 8, value: '京东支付' },
        { id: 9, value: '云闪付' },
        { id: 10, value: '余额+京东支付' },
        { id: 11, value: '余额+云闪付' },
        { id: 12, value: '百度支付' },
    ],
    welfarePayTypeFilters: [    //福利餐支付方式
        { id: 0, value: '用户账户余额' },
        { id: 1, value: '支付宝app支付' },
        { id: 2, value: '微信app支付' },
        { id: 3, value: '微信公众号支付' },
        { id: 4, value: '微信小程序支付' },
        { id: 5, value: '微信H5支付' },
        { id: 6, value: '支付宝H5支付' },
        { id: 7, value: '支付宝扫码支付' },
        { id: 8, value: '微信扫码支付' },
        { id: 9, value: '云闪付wap支付' },
        { id: 10, value: '云闪付app控件支付' },
        { id: 11, value: '京东wap支付' },
        { id: 12, value: '京东app支付' },
        { id: 13, value: '云闪付扫码支付' },
        { id: 14, value: '微信免密支付' },
    ],
    vipOrderPayTypeFilters: [    //平台包干套餐购买支付方式
        { id: 1, value: '支付宝' },
        { id: 2, value: '微信' },
        { id: 0, value: '余额支付' },
        { id: 10, value: '云闪付' },
        { id: 12, value: '京东支付' },
    ],
    rechargePayWayFilters: [    //支付商户-支付渠道-感谢费支付方式
        { id: 1, value: '支付宝' },
        { id: 2, value: '微信' },
        { id: 0, value: '余额支付' },
        { id: 10, value: '云闪付' },
        { id: 12, value: '京东支付' },
        { id: 15, value: '百度支付' },
    ],

    instantOrder22: [   //指定用车单 - 订单状态
        { id: 20, value: '待出发' },
        { id: 30, value: '行程中' },
        { id: 40, value: '行程结束' },
        { id: 50, value: '待付款' },
        { id: 60, value: '已完成' },
        { id: -50, value: '已关闭' },
    ],
    intercitySpecialLinePassengerOrderStatus: [ // 城际专线乘客--订单状态
        {id: 0, value: '等待应答'},
        {id: 10, value: '预约成功'},
        {id: 20, value: '等待接驾'},
        {id: 30, value: '行程中'},
        {id: 40, value: '行程结束'},
        {id: 60, value: '已完成'},
        {id: -20, value: '已关闭'},
    ],
    specialLineDriverOrderStatusFilters: [  //村村通订单状态
        { id: 0, value: '接单中' },
        { id: 10, value: '行程中' },
        { id: 20, value: '完成' },
        { id: -10, value: '取消' },
    ],
    orderPlatformFilters: [  // 下单来源
        { id: 0, value: 'APP 安卓下单' },
        { id: 10, value: 'APP IOS 下单' },
        { id: 20, value: 'H5 / 小程序下单' },
        { id: -10, value: '小程序下单' },
        { id: -10, value: 'H5 下单' },
    ],
    //普通网约车订单 - 费用明细 - 支付方式
    payRecordTypeFilters: [
        { id: 0, value: '用户账户余额' },
        { id: 1, value: '支付宝app支付' },
        { id: 2, value: '微信app支付' },
        { id: 3, value: '微信公众号支付' },
        { id: 4, value: '微信小程序支付' },
        { id: 5, value: '微信H5支付' },
        { id: 6, value: '支付宝H5支付' },
        { id: 7, value: '支付宝扫码支付' },
        { id: 8, value: '微信扫码支付' },
        { id: 9, value: '云闪付wap支付' },
        { id: 10, value: '云闪付app控件支付' },
        { id: 11, value: '京东wap支付' },
        { id: 12, value: '京东app支付' },
        { id: 13, value: '云闪付扫码支付' },
        { id: 14, value: '微信免密支付' },
        { id: 15, value: '百度支付' },
        { id: 16, value: '支付宝小程序支付' },
        { id: 17, value: '云闪付小程序支付' },
        { id: 100, value: '余额免密支付' },
    ],
    //普通网约车订单 - 费用明细 - 支付场景
    orderSceneFilters: [
        { id: 1, value: '订单支付' },
        { id: 70, value: '预支付' },
    ],
    //普通网约车订单 - 费用明细 - 支付状态
    enterprisePayStatusFilters: [
        { id: 0, value: '未支付' },
        { id: 1, value: '支付成功' },
        { id: 2, value: '支付失败' },
    ],
    welfarePayStatusFilters: [
        { id: 0, value: '未支付' },
        { id: 1, value: '支付成功' }
    ],
    //普通网约车订单 - 费用明细 - 订单退款方式
    orderRefundTypeFilters: [
        { id: 1, value: '原路返回' },
        { id: 6, value: '原路返回' },
        { id: 15, value: '原路返回' },
        { id: 16, value: '原路返回' },
        { id: 2, value: '微信' },
        { id: 3, value: '支付宝' },
        { id: 4, value: '余额' },
        { id: 7, value: '余额' },
        { id: 13, value: '余额' },
        { id: 14, value: '余额' },
    ],
    //普通网约车订单 - 费用明细 - 订单退款状态
    refundStatusFilters: [
        { id: 0, value: '未退款' },
        { id: 1, value: '已退款' },
    ],
    //普通网约车订单 - 派单日志 - 派单事件类型
    logTypeFilters: [
        { id: 10, value: '乘客下单' },
        { id: 20, value: '系统调度' },
        { id: 21, value: '重复呼单' },
        { id: 22, value: '重复派单' },
        { id: 25, value: '提醒预约单开始' },
        { id: 30, value: '系统调度推送' },
        { id: 40, value: '系统调度忽略' },
        { id: 50, value: '没有调度资源' },
        { id: 51, value: '调度资源' },
        { id: 60, value: '司机抢单成功' },
        { id: 70, value: '司机抢单失败' },
        { id: 71, value: '司机抢单超时' },
        { id: 80, value: 'APP超时忽略' },
        { id: 81, value: '主动忽略' },
        { id: 82, value: '抢单忽略' },
        { id: 83, value: '司机收车忽略' },
        { id: 90, value: '司机取消' },
        { id: 100, value: '乘客取消' },
        { id: 110, value: '系统取消' },
        { id: 200, value: '司机下单' },
        { id: 201, value: '乘客下单' },
        { id: 210, value: '乘客邀约' },
        { id: 220, value: '司机接受' },
        { id: 230, value: '预约成功' },
        { id: 240, value: '司机拒绝邀请' },
        { id: 250, value: '用户付款超时，系统自动取消' },
        { id: 260, value: '司机取消' },
        { id: 261, value: '司机取消单个乘客的订单' },
        { id: 270, value: '系统取消司机订单' },
        { id: 280, value: '用户取消' },
        { id: 290, value: '系统取消乘客订单' },
    ],
    //出租车车主类型
    taxiPartnerTagFilters: [
        { id: 1, value: '普通合伙人' },
        { id: 2, value: '巡游车合伙人' },
    ],
    //订单退款状态
    refundStateFilters: [
        { id: 1, value: '未退款' },
        { id: 2, value: '退款中' },
        { id: 3, value: '已退款' },
        { id: 4, value: '退款失败' },
    ],
    //村村通订单 - 乘客信息 - 下单来源
    senceTypeFilters: [
        { id: 11, value: '司机推广' },
        { id: 12, value: '预约下单' },
    ],
    //包干订单 - 基础信息 - 支付优惠方式
    payActivityTypeFilters: [
        { id: 1, value: '折扣减免' },
        { id: 2, value: '固定金额减免' },
    ],
    channelTypesFilters: [
        { id: 1, value: '万顺叫车平台' },
        { id: 10, value: '渠道商' },
        { id: 30, value: '开放平台' },
        { id: 40, value: '企业用车' }
    ],
    businessTypes: [ //业务类型
        {id: '10', value: '快车'},
        {id: '20', value: '专车'},
        {id: '30', value: '豪华车'},
        {id: '40', value: '商务车'},
        {id: '50', value: '出租车'},
    ],
    appointBusinessTypes: [ //预约单业务类型
        {id: '10', value: '快车'},
        {id: '20', value: '专车 '},
        {id: '30', value: '豪华车 '},
        {id: '40', value: '商务车 '},
    ],
    instantOrder20: [   //实时单 扫码单 出租车单 - 订单状态
        { id: 0, value: '等待应答' },
        { id: 10, value: '等待接驾' },
        { id: 20, value: '待出发' },
        { id: 30, value: '行程中' },
        { id: 40, value: '行程结束' },
        { id: 50, value: '待付款' },
        { id: 60, value: '已完成' },
        { id: -50, value: '已关闭' },
    ],
    instantOrder21: [   //预约单 包车 - 订单状态
        { id: 0, value: '等待应答' },
        { id: 10, value: '预约成功' },
        { id: 11, value: '等待接驾' },
        { id: 20, value: '待出发' },
        { id: 30, value: '行程中' },
        { id: 40, value: '行程结束' },
        { id: 50, value: '待付款' },
        { id: 60, value: '已完成' },
        { id: -20, value: '已关闭' },
    ],
    orderVipTypeFilters: [
        { id: 0, value: '非包干订单' },
        { id: 1, value: '包干订单' },
    ],
    platformFilters:[
        {id: 1, value: 'APP 安卓下单'},
        {id: 2, value: 'APP IOS下单'},
        {id: 3, value: 'H5 / 小程序下单 '},
        {id: 4, value: '小程序下单 '},
        {id: 5, value: 'H5 下单'},
        {id: 6, value: '百度小程序'},
        {id: 7, value: '后台下单'},
    ],
    partnerTapeFilters: [
        { id: 1, value: '普通车主' },
        { id: 2, value: '共享合伙人 ' },
        { id: 3, value: '高级合伙人 ' }
    ],
    driverLevelFilters: [
        { id: 0, value: 'A类' },
        { id: 1, value: 'B类' },
        { id: 2, value: 'C类' },
        { id: 3, value: 'D类' },
    ],
    isRepairFilters: [
        { id: 1, value: '是' },
        { id: 0, value: '否' },
    ],
    charingTypeFilters: [
        { id: 1, value: '实时计价' },
    ],
    passengerPayScenFilters: [  //乘客支付场景
        { id: 1, value: '订单付款' },
        { id: 70, value: '预支付' },
    ],
    payStaticFilters: [   //收款码支付方式
        { id: 0, value: '余额支付' },
        { id: 1, value: '支付宝app' },
        { id: 2, value: '微信app' },
        { id: 3, value: '余额' },
        { id: 4, value: '混合支付微信app' },
        { id: 5, value: '混合支付支付宝app' },
        { id: 7, value: '支付宝h5' },
        { id: 8, value: '微信h5' },
        { id: 9, value: '微信公众号h5' },
        { id: 10, value: '混合支付支付宝h5' },
        { id: 11, value: '混合支付微信h5' },
        { id: 12, value: '混合支付微信公众号h5' },
        { id: 13, value: '微信小程序支付' },
        { id: 14, value: '混合微信小程序支付' },
        { id: 15, value: '企业支付' },
        { id: 16, value: '开放平台支付' },
        { id: 17, value: '京东app支付' },
        { id: 18, value: '京东WAP支付' },
        { id: 19, value: '云闪付app支付' },
        { id: 20, value: '云闪付WAP支付' },
        { id: 21, value: '混合京东app支付' },
        { id: 22, value: '混合京东WAP支付' },
        { id: 23, value: '混合云闪付app支付' },
        { id: 24, value: '混合云闪付WAP支付' },
        { id: 25, value: '银联快捷支付' },
        { id: 100, value: '余额免密' },
        { id: 101, value: '微信app免密' },
        { id: 102, value: '支付宝app免密' },
    ],
    payTypeFilters: [
        { id: 0, value: '余额支付' },
        { id: 1, value: '支付宝app支付' },
        { id: 2, value: '微信app支付' },
        { id: 3, value: '微信公众号支付' },
        { id: 4, value: '微信小程序支付' },
        { id: 5, value: '微信H5支付' },
        { id: 6, value: '支付宝H5支付' },
        { id: 7, value: '支付宝扫码支付' },
        { id: 8, value: '微信扫码支付' },
        { id: 9, value: '云闪付wap支付' },
        { id: 10, value: '云闪付app控件支付' },
        { id: 11, value: '京东wap支付' },
        { id: 12, value: '京东app支付' },
        { id: 13, value: '云闪付扫码支付' },
        { id: 14, value: '微信免密支付' },
        { id: 15, value: '百度支付' },
        { id: 16, value: '支付宝小程序支付' },
        { id: 17, value: '云闪付小程序支付' },
    ],
    activityTypeFilters: [  //活动类型
        { id: 1, value: '注册送' },
        { id: 2, value: '单笔消费' },
        { id: 3, value: '支付立减' },
        { id: 4, value: '兑换码' },
        { id: 5, value: '定向送' },
        { id: 6, value: '万顺福卡' },
        { id: 7, value: '充值送' },
        { id: 8, value: '推荐奖励' },
        { id: 9, value: '支付活动' },
        { id: 10, value: '平台推广' },
        { id: 11, value: '兑换/抽奖' },
    ],
    settleTypesFilters: [
        { id: 10, value: '巡游车车费收入' },
        { id: 12, value: '二维码巡游车车费' },
        { id: 20, value: '网约车车费' },
        { id: 22, value: '扫码起单' },
        { id: 23, value: '网约车预付车费' },
        { id: 24, value: '网约车尾款车费' },
        { id: 26, value: '包车尾款' },
        { id: 27, value: '包车车费' },
        { id: 30, value: '分享推荐奖励' },
        { id: 40, value: '活动奖励' },
        { id: 50, value: '补款' },
        { id: 60, value: '提现失败返还' },
        { id: 70, value: '提现手续费返还' },
        { id: 80, value: '提现' },
        { id: 90, value: '老系统余额' },
        { id: 100, value: '异常单补款' },
        { id: 101, value: '异常单扣款' },
        { id: 102, value: '异常单退款' },
        { id: 110, value: '转借入' },
        { id: 120, value: '借入利息' },
        { id: 130, value: '借入终止' },
        { id: 140, value: '借入终止利息扣款' },
        { id: 200, value: '街坊专车车费' },
        { id: 201, value: '专车尾款车费' },
        { id: 202, value: '专车预付车费' },
        { id: 300, value: '感谢红包' },
        { id: 410, value: '刷单扣款' },
        { id: 420, value: '投诉扣款' },
        { id: 430, value: '异常扣款' },
        { id: 450, value: '提现手续费' },
        { id: 460, value: '取消订单扣款' },
        { id: 500, value: '司机包干流水' },
        { id: 510, value: '充值送推荐奖励' },
        { id: 520, value: '万顺福卡推荐奖励' },
        { id: 530, value: '平台费包干推荐奖励' },
        { id: 550, value: '包干订单退款' },
        { id: 560, value: '平台费包干推荐奖励回收' },
        { id: 570, value: '冲单奖' },
        { id: 571, value: '增单奖' },
        { id: 573, value: '活动奖励' },
        { id: 600, value: '村村通拼车车费' },
        { id: 610, value: '运力合作订单车费' },
        { id: 574, value: '推广码推荐注册' },
        { id: 575, value: '推广码推荐下单' },
    ],
    passengerRefundStateFilters: [
        { id: 0, value: '未退款' },
        { id: 1, value: '退款成功' },
    ],
    businessTypeFilters: [ //业务类型
        { id: 10, value: '快车' },
        { id: 20, value: '专车' },
        { id: 30, value: '豪华车' },
        { id: 40, value: '商务车' },
        { id: 50, value: '出租车' },
    ],
    scoreFilters: [
        { id: 1, value: '一星' },
        { id: 2, value: '二星' },
        { id: 3, value: '三星' },
        { id: 4, value: '四星' },
        { id: 5, value: '五星' },
    ],
    orderLaberFilters: [
        {id: 1, value: "实时订单"},
        {id: 2, value: "终端订单"},
        {id: 3, value: "邀约订单"},
        {id: 4, value: "一口价订单"},
        {id: 5, value: "助老模式订单"},
        {id: 6, value: "接机订单"},
        {id: 7, value: "送机订单"},
        {id: 8, value: "后台下单(邀约单)"},
        {id: 9, value: "企业用车(自主下单)"},
        {id: 10, value: "企业用车(邀约单)"},
        {id: 11, value: "万顺云办公自主下单"},
        {id: 12, value: "预约订单"},
        {id: 13, value: "包车订单"},
        {id: 14, value: "顺路单"},
    ],
    payFilters: [{
        id: 1,
        value: '支付宝'
    },
    {
        id: 2,
        value: '微信'
    },
    {
        id: 0,
        value: '余额支付'
    },
    {
        id: 10,
        value: '云闪付'
    },
    {
        id: 12,
        value: '京东支付'
    },
    {
        id: 201,
        value: '赠送'
    },
    {
        id: 202,
        value: '退款'
    },
    {
        id: 15,
        value: '百度支付'
    }
    ],
    cancelTypeFilters: [
        { id: 1, value: '乘客取消' },
        { id: 2, value: '车主取消' },
        { id: 3, value: '系统取消' },
        { id: 4, value: '后台取消' }
    ],
    instantOrder20Filters:[
        {id: 0, value: '等待应答'},
        {id: 10, value: '等待接驾'},
        {id: 20, value: '待出发'},
        {id: 30, value: '行程中'},
        {id: 40, value: '行程结束'},
        {id: 50, value: '待付款'},
        {id: 60, value: '已完成'},
        {id: -50, value: '已关闭'},
    ],
    instantOrder21Filters:[
        { id: 0, value: '等待应答' },
        { id: 10, value: '预约成功' },
        { id: 11, value: '等待接驾' },
        { id: 20, value: '待出发' },
        { id: 30, value: '行程中' },
        { id: 40, value: '行程结束' },
        { id: 50, value: '待付款' },
        { id: 60, value: '已完成' },
        { id: -20, value: '已关闭' }
    ],
    // 预约单订单标签
    orderdriverFilters: [
        {id: 1, value: '后台自主下单'},
        {id: 2, value: '企业用车 '},
        {id: 3, value: 'APP自主下单'},
        {id: 4, value: '邀约订单'},
    ],
    // 实时单订单标签
    realtimeorderFilters:[
      {id: 1, value: '后台自主下单'},
      {id: 3, value: 'APP自主下单'},
      {id: 4, value: '邀约订单'}
    ],
    //包车订单标签
    charterorderFilters:[
      {id: 1, value: '后台自主下单'},
      {id: 2, value: '企业用车'},
    ],
    //城际订单标签
    cityorderFilters:[
      {id: 1, value: '后台自主下单'},
    ],
    driverInfo: null,
    scenesTypeFilters: [
        {id: 1, value: '--'},
        {id: 2, value: '接机'},
        {id: 3, value: '送机'},
    ],
    wearMaskFilters: [  // 是否戴口罩
        {id: 0, value: '否'},
        {id: 1, value: '是'},
        {id: '-', value: '-'},
    ]
}

export default state;
