export const roundtripFilters = state => state.roundtripFilters // 里程往返
export const singleStateFilters = state => state.singleStateFilters // 派单状态
export const requestRideTypeFilters = state => state.requestRideTypeFilters // 服务类型
export const businessTypes = state => state.businessTypes // 业务类型
export const driverOrderStatusFilters = state => state.driverOrderStatusFilters // 司机订单状态
export const passengerOrderStatusFilters = state => state.passengerOrderStatusFilters // 乘客订单状态
export const settleTypeFilters = state => state.settleTypeFilters // 城际专线-结算类型
export const driverLevelFilters = state => state.driverLevelFilters // 城际专线-交委运管类型
export const paltformFilters = state => state.paltformFilters // 城际专线-下单来源
export const channelTypesFilters = state => state.channelTypesFilters // 城际专线-渠道类型
export const refundRecordStatesFilters = state => state.refundRecordStatesFilters // 城际专线-退款状态
export const payStatusFilters = state => state.payStatusFilters // 城际专线-支付状态
export const partnerTypeFilters = state => state.partnerTypeFilters // 城际专线-合伙人类型
export const vipTypeFilters = state => state.vipTypeFilters // 城际专线-司机类型
export const cancelReasonFilters = state => state.cancelReasonFilters // 城际专线-取消类型
export const cityorderFilters = state => state.cityorderFilters // 城际专线-取消类型
export const passengerpayStatusFilters = state => state.passengerpayStatusFilters // 城际专线-支付状态
